scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      type: laser_filters/LaserScanSpeckleFilter
      name: speckle_filter
      params:
        filter_type: 0
        max_range: 2.0
        max_range_difference: 0.1
        filter_window: 2